### ISSUE TITLE
drop localStorage usage in Hoodie Client

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/camp#101]
### ❓ The Motivation

When thinking about Hoodie’s APIs, we always tried to come up with the most simple ones without worrying about complexities in implementation, we call this [Dreamcode](http://hood.ie/initiatives/#dreamcode). One aspect of that simplicity was that some of the API is synchronous, for example

- `hoodie.account.id`
- `hoodie.account.isSignedIn()`
- `hoodie.store.hasLocalChanges()`
- `hoodie.connectionStatus.ok`

We want to keep these APIs, but in order to make that possible, we have to introduce an asynchronous initialisation, similar to [jQuery’s ready](https://api.jquery.com/ready/) or [serviceWorker.ready](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/ready), as we realised that we no longer can rely on localStorage, which is the only synchronous API to read/write data.

Our problem with localStorage is that it is not accessible in ServiceWorker. But as we want Hoodie to be a great solution for Offline First applications, we have to make ServiceWorker support a priority.

So instead of this:

```html
<script src="hoodie/client.js"></script>
<script>
if (hoodie.account.isSignedIn()) {
  renderDashboard()
} else {
  renderWelcome()
}
</script>
```

We will from now on have to do 

```html
<script src="hoodie/client.js"></script>
<script>
hoodie.ready.then(function () {
  if (hoodie.account.isSignedIn()) {
    renderDashboard()
  } else {
    renderWelcome()
  }
})
</script>
```

### :clipboard: Steps

- [x] create generic library for hook APIs: https://github.com/gr2m/before-after-hook
- [x] (https://github.com/hoodiehq/hoodie-account-client/pull/125) `@hoodie/client-account`: replace undocumented `pre:*` and `post:*` events with a hook API for `signin` and `signout`
- [x] (https://github.com/hoodiehq/hoodie-client/pull/112) use hook library in [@hoodie/client](https://github.com/hoodiehq/hoodie-client/blob/a4e3544c889cd3145f37ab837adb70ad1ce04ac9/lib/init.js#L11-L72) instead of current workaround with `pre:*` and `post:*` API
- [x] (https://github.com/hoodiehq/hoodie-store-client/pull/140) remove localStorage dependency from `@hoodie/store-client`
- [x] Implement lazy initialisation with `.ready` property similar to [serviceWorker.ready](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/ready) and `.hook.{before,after}('ready', method)` API
  - [x] (https://github.com/hoodiehq/hoodie-account-client/pull/129) in `@hoodie/account-client`
  - [x] (hoodiehq/hoodie-connection-status#60) in `@hoodie/connection-status`
  - [x] (https://github.com/hoodiehq/hoodie-client/pull/110) in `@hoodie/client`
- [x] Implement optional `options.store.{get,set,unset}` argument with async get/set/unset methods (default to implementation using `humble-localstorage` returning promises)
  - [x] (https://github.com/hoodiehq/hoodie-account-client/pull/129) in `@hoodie/account-client`
  - [x] (hoodiehq/hoodie-connection-status#60) in `@hoodie/connection-status`
  - see https://github.com/gr2m/async-get-set-store
- [x] (https://www.npmjs.com/package/pouchdb-doc-api) Implement PouchDB plugin that exposes a APIs on a document level to get, set and unset
- [x] Drop `.hasLocalChanges()` API from`@hoodie/store-client` (https://github.com/hoodiehq/hoodie-store-client/issues/138)
- [x] release new breaking versions
  - [x] (hoodiehq/hoodie-account-client#126) `@hoodie/account-client`
  - [x] (hoodiehq/hoodie-store-client#140) `@hoodie/store-client`
  - [x] (hoodiehq/hoodie-connection-status#60) `@hoodie/connection-status`
  - [x] (hoodiehq/hoodie-client#110) `@hoodie/client`
- [x] update `hoodie` with new `@hoodie/client` and document changes
- [ ] update `hoodie-app-tracker` with new `hoodie` and fix usage

### Later

- [ ] `@hoodie/account-client`: remove `options.validate` in favor of a `signup` hook
